Repository projectsyn/lieutenant-operator, pull requests merged in 2021-08, with the labels that each got.

#184 Manage kind version via go.mod
  Makefile.vars.mk
  e2e/kind.mk
  go.mod
  go.sum
  tools.go
Labels: change

#185 Update K8s version to v1.21
  Makefile
  Makefile.vars.mk
Labels: dependency

#188 Register Gitlab implemenation
  controllers/gitrepo/steps.go
Labels: bug

#189 Fix spelling of lieutenant
  config/manager/manager.yaml
  e2e/definitions/operator/deployment.yaml
Labels: change

#190 Allow `controller-manager` to `list`, `get`, and `watch` TenantTemplates
  config/rbac/role.yaml
  controllers/tenant_controller.go
Labels: bug

#192 Fix typed nil assignment
  vault/client.go
Labels: bug

#193 Log vault errors and messages
  vault/client.go
  vault/log_adapter.go
Labels: enhancement

#194 Fix vault client logging
  vault/client.go
  vault/log_adapter.go
  vault/log_adapter_test.go
Labels: bug

#195 Adds recursive deletion of directories
  vault/client.go
  vault/client_test.go
Labels: bug

#196 Fix error when recreating git repository
  git/gitlab/gitlab.go
  git/gitlab/gitlab_test.go
Labels: bug

#197 Steps and status update debug logs
  pipeline/pipeline.go
  pipeline/steps.go
  pipeline/steps_test.go
Labels: enhancement

#199 Fix issue that blocked status updates
  api/v1alpha1/cluster_types.go
  api/v1alpha1/gitrepo_types.go
  api/v1alpha1/tenant_types.go
  pipeline/pipeline.go
  pipeline/steps.go
Labels: bug

#198 Add how-to on running the Operator locally
  Makefile
  docs/modules/ROOT/pages/how-tos/local-env.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
  e2e/.gitignore
  e2e/kind.mk
Labels: documentation

#201 Add dynamic fact field to CRD
  api/v1alpha1/cluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/syn.tools_clusters.yaml
  controllers/cluster/rbac.go
Labels: enhancement

#204 Fix git repository race condition
  controllers/cluster_controller.go
  controllers/gitrepo/utils.go
  controllers/tenant_controller.go
Labels: bug

#202 Remove all `context.TODO()`
  controllers/cluster/rbac.go
  controllers/cluster/role.go
  controllers/cluster/tenant.go
  controllers/cluster_controller.go
  controllers/gitrepo/steps.go
  controllers/gitrepo/template.go
  controllers/gitrepo/utils.go
  controllers/gitrepo_controller.go
  controllers/tenant/git.go
  controllers/tenant/role.go
  controllers/tenant/role_binding.go
  controllers/tenant/service_account.go
  controllers/tenant/template.go
  controllers/tenant_controller.go
  git/manager/manager.go
  pipeline/pipeline.go
  pipeline/steps.go
  vault/reconcile_steps.go
Labels: change

#205 Fix recreated service account token bug
  controllers/cluster/rbac.go
Labels: bug
