Repository projectsyn/lieutenant-operator, pull requests merged in 2024-07, with the labels that each got.

#285 Add CI variable management to GitRepo
  api/v1alpha1/gitrepo_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/syn.tools_clusters.yaml
  config/crd/bases/syn.tools_gitrepos.yaml
  config/crd/bases/syn.tools_tenants.yaml
  config/crd/bases/syn.tools_tenanttemplates.yaml
  controllers/gitrepo/steps.go
  controllers/gitrepo/steps_test.go
  controllers/gitrepo/watchers/ci_var_secret.go
  controllers/gitrepo/watchers/ci_var_secret_test.go
  controllers/gitrepo_controller.go
  controllers/tenant_controller.go
  docs/modules/ROOT/pages/references/api-reference.adoc
  git/gitlab/gitlab.go
  git/gitlab/gitlab_test.go
  git/gitlab/testdata/testGetUpdateServer/deploy_keys.json
  git/gitlab/testdata/testGetUpdateServer/projects_id_response.json
  git/gitlab/testdata/testGetUpdateServer/projects_path_response.json
  git/manager/manager.go
  go.mod
  go.sum
  main.go
Labels: enhancement

#290 Reconcile GitRepos every three hours
  controllers/gitrepo_controller.go
  main.go
Labels: enhancement

#293 Disentangle random environment variables
  controllers/cluster_controller.go
  controllers/gitrepo/utils.go
  controllers/gitrepo_controller.go
  controllers/tenant/git.go
  controllers/tenant_controller.go
  go.mod
  go.sum
  main.go
  pipeline/pipeline.go
  pipeline/steps.go
  pipeline/steps_test.go
  vault/reconcile_steps.go
  vault/reconcile_steps_test.go
Labels: enhancement

#292 Reconcile managed compile pipeline configuration
  api/v1alpha1/cluster_types.go
  api/v1alpha1/constants.go
  api/v1alpha1/tenant_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/syn.tools_clusters.yaml
  config/crd/bases/syn.tools_tenants.yaml
  config/crd/bases/syn.tools_tenanttemplates.yaml
  controllers/cluster_compile_pipeline_controller.go
  controllers/cluster_compile_pipeline_controller_test.go
  controllers/cluster_controller.go
  controllers/common_test.go
  controllers/tenant/git.go
  controllers/tenant/steps.go
  controllers/tenant_compile_pipeline_controller.go
  controllers/tenant_compile_pipeline_controller_test.go
  controllers/util.go
  docs/modules/ROOT/pages/references/api-reference.adoc
  main.go
Labels: enhancement

#295 Update Makefile `run` target to include parameters needed for most local setups
  Makefile
Labels: change

#297 Do not set CI variables as "protected"
  controllers/cluster_compile_pipeline_controller.go
  controllers/cluster_compile_pipeline_controller_test.go
  controllers/tenant_compile_pipeline_controller.go
  controllers/util.go
Labels: change

#298 Fix initialization of GitLab repos
  git/gitlab/gitlab.go
  git/gitlab/gitlab_test.go
Labels: bug

#299 Reconcile clusters on tenant change
  controllers/cluster_controller.go
Labels: bug

#301 Format `CLUSTERS` variable according to SDD.
  controllers/tenant_compile_pipeline_controller.go
  controllers/tenant_compile_pipeline_controller_test.go
Labels: bug
